### ISSUE TITLE
Game freeze

### ISSUE THREAD

**Issue by versgui** [esviji/esviji#163]
Sometimes and after a few seconds of play, the game freezes on level 2: no more cursor and unable to go back on menu screen.
It seems random, it's not systematic.

Android 5.1.1, One+ One.

![Freeze screenshot](https://pbs.twimg.com/media/CZCJivVW8AAsvHj.png)

**Comment by nhoizey** [comment]
If you have some that sleeps in your drawer, I need at least an Android device with Android 4.4+ on it to test such issues.

Because I have several iOS devices and 2 Firefox OS devices, but no Android yet, in my own Device Lab…

**Comment by SphinxKnight** [comment]
I had the same issue and noticed that it "sort of" started by shifting the viewport to the side. More testing soon (but no device sleeping here :/)

**Comment by nhoizey** [comment]
@SphinxKnight what do you mean by "shifting the viewport"? A kind of scroll, as reported in issue #162 ?

**Comment by SphinxKnight** [comment]
Yes, that's what I meant.

**Comment by nhoizey** [comment]
Ok, so I'll first try to fix #162, which is also visible on Safari iOS on my iPhone.

Thanks!

**Comment by nhoizey** [comment]
#162 is now fixed.

**Comment by borisschapira** [comment]
Android version. Esviji v2.1.5.
The issue are still there, just lost my launcher when my OnePlus One auto-activated the battery saver mode.

**Comment by nhoizey** [comment]
@borisschapira thanks for the (sad) information!

It means the WebView it not responsible for this. But the Chromium one should let me remote debug with my Mac's Chrome, which will help a lot.

**Comment by borisschapira** [comment]
What can I do to help ?

**Comment by nhoizey** [comment]
You can try to plug your One to your computer and see if you can activate remote debug in Chrome, to see if there are error messages in the console.

(there are CSP related error messages, you can ignore them)

**Comment by borisschapira** [comment]
I'm afraid I can't reproduce : don't know how to simultaneously consume battery and connect my phone to the computer. If I connect the phone, it starts charging… :-/

I'll try.

**Comment by nhoizey** [comment]
Oh, of course… ;-)

I think it happens whenever the focus is lost. Maybe just switching apps does it.

**Comment by nhoizey** [comment]
I have to be more careful with my commit messages… :-/

`Might be a way to fix #163` is interpreted as `fixes #163 -> close it` by Github…

**Comment by nhoizey** [comment]
2.1.11 released for beta testers (#170), may fix the issue.

**Comment by borisschapira** [comment]
I just updated to 2.1.11 and cannot launch the game anymore. I see the home screen and everything disappear before the bottom button are rendered.

**Comment by nhoizey** [comment]
The game is still there but empty, or it crashes?

**Comment by SphinxKnight** [comment]
Can reproduce here, start screen with "Play esviji on any device..." is still there but after that (few seconds) nothing but a gray screen :-/

**Comment by nhoizey** [comment]
Ok, looks like an issue with JavaScript of Modernizr features detection.

I will look into it, thanks for the report.

**Comment by nhoizey** [comment]
PhoneGap version abandoned: http://esviji.com/2016/02/android-and-ios-apps-development-stopped.html
